version: '3.8'
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastify
    ports:
      - '5433:5432'
    volumes:
      - pgdb:/var/lib/postgresql/data
      - './sql:/docker-entrypoint-initdb.d/'
volumes:
  pgdb:
    driver: local
